### ISSUE TITLE
Not exactly related... listing videos from a channel?

### ISSUE THREAD

**Issue by for-coursera** [codesoap/ytools#3]
Hi!

What would you say about may be adding a feature to `ytools` to retrieve a list of all the videos from a channel?

YouTube, of course, provides has an rss feed for it, with the following URL:

    https://www.youtube.com/feeds/videos.xml?channel_id=<CHANNELID_GOES_HERE>

But it lists only some (latest?) videos.. 

What do you think?

**Comment by codesoap** [comment]
No need for `ytools`, you can simply use `youtube-dl` to download whole channels. For example:

```bash
youtube-dl 'https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA/videos'

# If you don't want to download, but only list the videos use this:
youtube --get-title 'https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA/videos'
```

Is this what you are looking for?

**Comment by for-coursera** [comment]
Thanks again, that's exactly what I wanted :)
